@extends('layout')

@section('meta')
<meta name="keywords" content="国际国家代码与区号查询表,国家缩写,国家英文缩写,国家区号,时差">
<meta name="description" content="提供国际国家代码与区号查询表,国家缩写,国家英文缩写,国家区号,时差等的查询">
@stop

@section('title')
国际国家代码与区号查询表 - 在线JSON校验格式化工具(OK JSON)
@stop

@section('head_css')
<style>
    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
        border: 1px solid #ddd;
        /*line-height: 18px;*/
    }
    tr>td, tr>th{
        height: 30px;
        line-height: 30px;
        text-align: center;
    }
</style>
@stop


@section('content')
@include('tables.tab')

    <div class="panel panel-default">
    <div class="panel-heading">
        国际国家代码与区号查询
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <TABLE class="table table-bordered list">

            <TR>
                <th>Countries and Regions</th>
                <th>国家或地区</th>
                <th>国际域名缩写</th>
                <th>电话代码 </th>
                <th>时差</th>
            </TR>
            <TR>
                <TD>Angola</TD>
                <TD>安哥拉</TD>
                <TD>AO</TD>
                <TD>244</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Afghanistan</TD>
                <TD>阿富汗</TD>
                <TD>AF</TD>
                <TD>93</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Albania</TD>
                <TD>阿尔巴尼亚</TD>
                <TD>AL</TD>
                <TD>355</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Algeria</TD>
                <TD>阿尔及利亚</TD>
                <TD>DZ</TD>
                <TD>213</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Andorra</TD>
                <TD>安道尔共和国</TD>
                <TD>AD</TD>
                <TD>376</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Anguilla</TD>
                <TD>安圭拉岛</TD>
                <TD>AI</TD>
                <TD>1264</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Antigua and Barbuda</TD>
                <TD>安提瓜和巴布达</TD>
                <TD>AG</TD>
                <TD>1268</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Argentina</TD>
                <TD>阿根廷</TD>
                <TD>AR</TD>
                <TD>54</TD>
                <TD>-11</TD>
            </TR>
            <TR>
                <TD>Armenia</TD>
                <TD>亚美尼亚</TD>
                <TD>AM</TD>
                <TD>374</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Ascension</TD>
                <TD>阿森松</TD>
                <TD>&nbsp;</TD>
                <TD>247</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Australia</TD>
                <TD>澳大利亚</TD>
                <TD>AU</TD>
                <TD>61</TD>
                <TD>+2</TD>
            </TR>
            <TR>
                <TD>Austria</TD>
                <TD>奥地利</TD>
                <TD>AT</TD>
                <TD>43</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Azerbaijan</TD>
                <TD>阿塞拜疆</TD>
                <TD>AZ</TD>
                <TD>994</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Bahamas</TD>
                <TD>巴哈马</TD>
                <TD>BS</TD>
                <TD>1242</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Bahrain</TD>
                <TD>巴林</TD>
                <TD>BH</TD>
                <TD>973</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Bangladesh</TD>
                <TD>孟加拉国</TD>
                <TD>BD</TD>
                <TD>880</TD>
                <TD>-2</TD>
            </TR>
            <TR>
                <TD>Barbados</TD>
                <TD>巴巴多斯</TD>
                <TD>BB</TD>
                <TD>1246</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Belarus</TD>
                <TD>白俄罗斯</TD>
                <TD>BY</TD>
                <TD>375</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Belgium</TD>
                <TD>比利时</TD>
                <TD>BE</TD>
                <TD>32</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Belize</TD>
                <TD>伯利兹</TD>
                <TD>BZ</TD>
                <TD>501</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Benin</TD>
                <TD>贝宁</TD>
                <TD>BJ</TD>
                <TD>229</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Bermuda Is.</TD>
                <TD>百慕大群岛</TD>
                <TD>BM</TD>
                <TD>1441</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Bolivia</TD>
                <TD>玻利维亚</TD>
                <TD>BO</TD>
                <TD>591</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Botswana</TD>
                <TD>博茨瓦纳</TD>
                <TD>BW</TD>
                <TD>267</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Brazil</TD>
                <TD>巴西</TD>
                <TD>BR</TD>
                <TD>55</TD>
                <TD>-11</TD>
            </TR>
            <TR>
                <TD>Brunei</TD>
                <TD>文莱</TD>
                <TD>BN</TD>
                <TD>673</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Bulgaria</TD>
                <TD>保加利亚</TD>
                <TD>BG</TD>
                <TD>359</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Burkina-faso</TD>
                <TD>布基纳法索</TD>
                <TD>BF</TD>
                <TD>226</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Burma</TD>
                <TD>缅甸</TD>
                <TD>MM</TD>
                <TD>95</TD>
                <TD>-1.3</TD>
            </TR>
            <TR>
                <TD>Burundi</TD>
                <TD>布隆迪</TD>
                <TD>BI</TD>
                <TD>257</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Cameroon</TD>
                <TD>喀麦隆</TD>
                <TD>CM</TD>
                <TD>237</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Canada</TD>
                <TD>加拿大</TD>
                <TD>CA</TD>
                <TD>1</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Cayman Is.</TD>
                <TD>开曼群岛</TD>
                <TD>&nbsp;</TD>
                <TD>1345</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Central African Republic</TD>
                <TD>中非共和国</TD>
                <TD>CF</TD>
                <TD>236</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Chad</TD>
                <TD>乍得</TD>
                <TD>TD</TD>
                <TD>235</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Chile</TD>
                <TD>智利</TD>
                <TD>CL</TD>
                <TD>56</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>China</TD>
                <TD>中国</TD>
                <TD>CN</TD>
                <TD>86</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Colombia</TD>
                <TD>哥伦比亚</TD>
                <TD>CO</TD>
                <TD>57</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Congo</TD>
                <TD>刚果</TD>
                <TD>CG</TD>
                <TD>242</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Cook Is.</TD>
                <TD>库克群岛</TD>
                <TD>CK</TD>
                <TD>682</TD>
                <TD>-18.3</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Costa Rica</TD>
                <TD>哥斯达黎加</TD>
                <TD>CR</TD>
                <TD>506</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Cuba</TD>
                <TD>古巴</TD>
                <TD>CU</TD>
                <TD>53</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Cyprus</TD>
                <TD>塞浦路斯</TD>
                <TD>CY</TD>
                <TD>357</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Czech Republic </TD>
                <TD>捷克</TD>
                <TD>CZ</TD>
                <TD>420</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Denmark</TD>
                <TD>丹麦</TD>
                <TD>DK</TD>
                <TD>45</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Djibouti</TD>
                <TD>吉布提</TD>
                <TD>DJ</TD>
                <TD>253</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Dominica Rep.</TD>
                <TD>多米尼加共和国</TD>
                <TD>DO</TD>
                <TD>1890</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Ecuador</TD>
                <TD>厄瓜多尔</TD>
                <TD>EC</TD>
                <TD>593</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Egypt</TD>
                <TD>埃及</TD>
                <TD>EG</TD>
                <TD>20</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>EI Salvador</TD>
                <TD>萨尔瓦多</TD>
                <TD>SV</TD>
                <TD>503</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Estonia</TD>
                <TD>爱沙尼亚</TD>
                <TD>EE</TD>
                <TD>372</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Ethiopia</TD>
                <TD>埃塞俄比亚</TD>
                <TD>ET</TD>
                <TD>251</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Fiji</TD>
                <TD>斐济</TD>
                <TD>FJ</TD>
                <TD>679</TD>
                <TD>+4</TD>
            </TR>
            <TR>
                <TD>Finland</TD>
                <TD>芬兰</TD>
                <TD>FI</TD>
                <TD>358</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>France</TD>
                <TD>法国</TD>
                <TD>FR</TD>
                <TD>33</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>French Guiana</TD>
                <TD>法属圭亚那</TD>
                <TD>GF</TD>
                <TD>594</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Gabon</TD>
                <TD>加蓬</TD>
                <TD>GA</TD>
                <TD>241</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Gambia</TD>
                <TD>冈比亚</TD>
                <TD>GM</TD>
                <TD>220</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Georgia </TD>
                <TD>格鲁吉亚</TD>
                <TD>GE</TD>
                <TD>995</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Germany </TD>
                <TD>德国</TD>
                <TD>DE</TD>
                <TD>49</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Ghana</TD>
                <TD>加纳</TD>
                <TD>GH</TD>
                <TD>233</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Gibraltar</TD>
                <TD>直布罗陀</TD>
                <TD>GI</TD>
                <TD>350</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Greece</TD>
                <TD>希腊</TD>
                <TD>GR</TD>
                <TD>30</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Grenada</TD>
                <TD>格林纳达</TD>
                <TD>GD</TD>
                <TD>1809</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Guam</TD>
                <TD>关岛</TD>
                <TD>GU</TD>
                <TD>1671</TD>
                <TD>+2</TD>
            </TR>
            <TR>
                <TD>Guatemala</TD>
                <TD>危地马拉</TD>
                <TD>GT</TD>
                <TD>502</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Guinea</TD>
                <TD>几内亚</TD>
                <TD>GN</TD>
                <TD>224</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Guyana</TD>
                <TD>圭亚那</TD>
                <TD>GY</TD>
                <TD>592</TD>
                <TD>-11</TD>
            </TR>
            <TR>
                <TD>Haiti</TD>
                <TD>海地</TD>
                <TD>HT</TD>
                <TD>509</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Honduras</TD>
                <TD>洪都拉斯</TD>
                <TD>HN</TD>
                <TD>504</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Hongkong</TD>
                <TD>香港</TD>
                <TD>HK</TD>
                <TD>852</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Hungary</TD>
                <TD>匈牙利</TD>
                <TD>HU</TD>
                <TD>36</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Iceland</TD>
                <TD>冰岛</TD>
                <TD>IS</TD>
                <TD>354</TD>
                <TD>-9</TD>
            </TR>
            <TR>
                <TD>India</TD>
                <TD>印度</TD>
                <TD>IN</TD>
                <TD>91</TD>
                <TD>-2.3</TD>
            </TR>
            <TR>
                <TD>Indonesia</TD>
                <TD>印度尼西亚</TD>
                <TD>ID</TD>
                <TD>62</TD>
                <TD>-0.3</TD>
            </TR>
            <TR>
                <TD>Iran</TD>
                <TD>伊朗</TD>
                <TD>IR</TD>
                <TD>98</TD>
                <TD>-4.3</TD>
            </TR>
            <TR>
                <TD>Iraq</TD>
                <TD>伊拉克</TD>
                <TD>IQ</TD>
                <TD>964</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Ireland</TD>
                <TD>爱尔兰</TD>
                <TD>IE</TD>
                <TD>353</TD>
                <TD>-4.3</TD>
            </TR>
            <TR>
                <TD>Israel</TD>
                <TD>以色列</TD>
                <TD>IL</TD>
                <TD>972</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Italy</TD>
                <TD>意大利</TD>
                <TD>IT</TD>
                <TD>39</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Ivory Coast</TD>
                <TD>科特迪瓦</TD>
                <TD>&nbsp;</TD>
                <TD>225</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Jamaica</TD>
                <TD>牙买加</TD>
                <TD>JM</TD>
                <TD>1876</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Japan</TD>
                <TD>日本</TD>
                <TD>JP</TD>
                <TD>81</TD>
                <TD>+1</TD>
            </TR>
            <TR>
                <TD>Jordan</TD>
                <TD>约旦</TD>
                <TD>JO</TD>
                <TD>962</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Kampuchea (Cambodia )</TD>
                <TD>柬埔寨</TD>
                <TD>KH</TD>
                <TD>855</TD>
                <TD>-1</TD>
            </TR>
            <TR>
                <TD>Kazakstan</TD>
                <TD>哈萨克斯坦</TD>
                <TD>KZ</TD>
                <TD>327</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Kenya</TD>
                <TD>肯尼亚</TD>
                <TD>KE</TD>
                <TD>254</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Korea</TD>
                <TD>韩国</TD>
                <TD>KR</TD>
                <TD>82</TD>
                <TD>+1</TD>
            </TR>
            <TR>
                <TD>Kuwait</TD>
                <TD>科威特</TD>
                <TD>KW</TD>
                <TD>965</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Kyrgyzstan </TD>
                <TD>吉尔吉斯坦</TD>
                <TD>KG</TD>
                <TD>331</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Laos</TD>
                <TD>老挝</TD>
                <TD>LA</TD>
                <TD>856</TD>
                <TD>-1</TD>
            </TR>
            <TR>
                <TD>Latvia </TD>
                <TD>拉脱维亚</TD>
                <TD>LV</TD>
                <TD>371</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Lebanon</TD>
                <TD>黎巴嫩</TD>
                <TD>LB</TD>
                <TD>961</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Lesotho</TD>
                <TD>莱索托</TD>
                <TD>LS</TD>
                <TD>266</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Liberia</TD>
                <TD>利比里亚</TD>
                <TD>LR</TD>
                <TD>231</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Libya</TD>
                <TD>利比亚</TD>
                <TD>LY</TD>
                <TD>218</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Liechtenstein</TD>
                <TD>列支敦士登</TD>
                <TD>LI</TD>
                <TD>423</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Lithuania</TD>
                <TD>立陶宛</TD>
                <TD>LT</TD>
                <TD>370</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Luxembourg</TD>
                <TD>卢森堡</TD>
                <TD>LU</TD>
                <TD>352</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Macao</TD>
                <TD>澳门</TD>
                <TD>MO</TD>
                <TD>853</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Madagascar</TD>
                <TD>马达加斯加</TD>
                <TD>MG</TD>
                <TD>261</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Malawi</TD>
                <TD>马拉维</TD>
                <TD>MW</TD>
                <TD>265</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Malaysia</TD>
                <TD>马来西亚</TD>
                <TD>MY</TD>
                <TD>60</TD>
                <TD>-0.5</TD>
            </TR>
            <TR>
                <TD>Maldives</TD>
                <TD>马尔代夫</TD>
                <TD>MV</TD>
                <TD>960</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Mali</TD>
                <TD>马里</TD>
                <TD>ML</TD>
                <TD>223</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Malta</TD>
                <TD>马耳他</TD>
                <TD>MT</TD>
                <TD>356</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Mariana Is</TD>
                <TD>马里亚那群岛</TD>
                <TD>&nbsp;</TD>
                <TD>1670</TD>
                <TD>+1</TD>
            </TR>
            <TR>
                <TD>Martinique</TD>
                <TD>马提尼克</TD>
                <TD>&nbsp;</TD>
                <TD>596</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Mauritius</TD>
                <TD>毛里求斯</TD>
                <TD>MU</TD>
                <TD>230</TD>
                <TD>-4</TD>
            </TR>
            <TR>
                <TD>Mexico</TD>
                <TD>墨西哥</TD>
                <TD>MX</TD>
                <TD>52</TD>
                <TD>-15</TD>
            </TR>
            <TR>
                <TD>Moldova Republic of </TD>
                <TD>摩尔多瓦</TD>
                <TD>MD</TD>
                <TD>373</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Monaco</TD>
                <TD>摩纳哥</TD>
                <TD>MC</TD>
                <TD>377</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Mongolia </TD>
                <TD>蒙古</TD>
                <TD>MN</TD>
                <TD>976</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Montserrat Is</TD>
                <TD>蒙特塞拉特岛</TD>
                <TD>MS</TD>
                <TD>1664</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Morocco</TD>
                <TD>摩洛哥</TD>
                <TD>MA</TD>
                <TD>212</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Mozambique</TD>
                <TD>莫桑比克</TD>
                <TD>MZ</TD>
                <TD>258</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Namibia </TD>
                <TD>纳米比亚</TD>
                <TD>NA</TD>
                <TD>264</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Nauru</TD>
                <TD>瑙鲁</TD>
                <TD>NR</TD>
                <TD>674</TD>
                <TD>+4</TD>
            </TR>
            <TR>
                <TD>Nepal</TD>
                <TD>尼泊尔</TD>
                <TD>NP</TD>
                <TD>977</TD>
                <TD>-2.3</TD>
            </TR>
            <TR>
                <TD>Netheriands Antilles</TD>
                <TD>荷属安的列斯</TD>
                <TD>&nbsp;</TD>
                <TD>599</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Netherlands</TD>
                <TD>荷兰</TD>
                <TD>NL</TD>
                <TD>31</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>New Zealand</TD>
                <TD>新西兰</TD>
                <TD>NZ</TD>
                <TD>64</TD>
                <TD>+4</TD>
            </TR>
            <TR>
                <TD>Nicaragua</TD>
                <TD>尼加拉瓜</TD>
                <TD>NI</TD>
                <TD>505</TD>
                <TD>-14</TD>
            </TR>
            <TR>
                <TD>Niger</TD>
                <TD>尼日尔</TD>
                <TD><FONT face=宋体>NE</TD>
                <TD>227</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Nigeria</TD>
                <TD>尼日利亚</TD>
                <TD>NG</TD>
                <TD>234</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>North Korea</TD>
                <TD>朝鲜</TD>
                <TD>KP</TD>
                <TD>850</TD>
                <TD>+1</TD>
            </TR>
            <TR>
                <TD>Norway</TD>
                <TD>挪威</TD>
                <TD>NO</TD>
                <TD>47</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Oman</TD>
                <TD>阿曼</TD>
                <TD>OM</TD>
                <TD>968</TD>
                <TD>-4</TD>
            </TR>
            <TR>
                <TD>Pakistan</TD>
                <TD>巴基斯坦</TD>
                <TD>PK</TD>
                <TD>92</TD>
                <TD>-2.3</TD>
            </TR>
            <TR>
                <TD>Panama</TD>
                <TD>巴拿马</TD>
                <TD>PA</TD>
                <TD>507</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Papua New
                        Cuinea</TD>
                <TD>巴布亚新几内亚</TD>
                <TD>PG</TD>
                <TD>675</TD>
                <TD>+2</TD>
            </TR>
            <TR>
                <TD>Paraguay</TD>
                <TD>巴拉圭</TD>
                <TD>PY</TD>
                <TD>595</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Peru</TD>
                <TD>秘鲁</TD>
                <TD>PE</TD>
                <TD>51</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Philippines</TD>
                <TD>菲律宾</TD>
                <TD>PH</TD>
                <TD>63</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Poland</TD>
                <TD>波兰</TD>
                <TD>PL</TD>
                <TD>48</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>French Polynesia</TD>
                <TD>法属玻利尼西亚</TD>
                <TD>PF</TD>
                <TD>689</TD>
                <TD>+3</TD>
            </TR>
            <TR>
                <TD>Portugal</TD>
                <TD>葡萄牙</TD>
                <TD>PT</TD>
                <TD>351</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Puerto Rico</TD>
                <TD>波多黎各</TD>
                <TD>PR</TD>
                <TD>1787</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Qatar</TD>
                <TD>卡塔尔</TD>
                <TD>QA</TD>
                <TD>974</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Reunion</TD>
                <TD>留尼旺</TD>
                <TD>&nbsp;</TD>
                <TD>262</TD>
                <TD>-4</TD>
            </TR>
            <TR>
                <TD>Romania</TD>
                <TD>罗马尼亚</TD>
                <TD>RO</TD>
                <TD>40</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Russia</TD>
                <TD>俄罗斯</TD>
                <TD>RU</TD>
                <TD>7</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Saint Lueia</TD>
                <TD>圣卢西亚</TD>
                <TD>LC</TD>
                <TD>1758</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Saint Vincent</TD>
                <TD>圣文森特岛</TD>
                <TD>VC</TD>
                <TD>1784</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Samoa Eastern</TD>
                <TD>东萨摩亚(美)</TD>
                <TD>&nbsp;</TD>
                <TD>684</TD>
                <TD>-19</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Samoa Western</TD>
                <TD>西萨摩亚</TD>
                <TD>&nbsp;</TD>
                <TD>685</TD>
                <TD>-19</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>San Marino</TD>
                <TD>圣马力诺</TD>
                <TD>SM</TD>
                <TD>378</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Sao Tome
                        and Principe</TD>
                <TD>圣多美和普林西比</TD>
                <TD>ST</TD>
                <TD>239</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Saudi Arabia</TD>
                <TD>沙特阿拉伯</TD>
                <TD>SA</TD>
                <TD>966</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Senegal</TD>
                <TD>塞内加尔</TD>
                <TD>SN</TD>
                <TD>221</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Seychelles</TD>
                <TD>塞舌尔</TD>
                <TD>SC</TD>
                <TD>248</TD>
                <TD>-4</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Sierra Leone</TD>
                <TD>塞拉利昂</TD>
                <TD>SL</TD>
                <TD>232</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Singapore</TD>
                <TD>新加坡</TD>
                <TD>SG</TD>
                <TD>65</TD>
                <TD>+0.3</TD>
            </TR>
            <TR>
                <TD>Slovakia</TD>
                <TD>斯洛伐克</TD>
                <TD>SK</TD>
                <TD>421</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Slovenia</TD>
                <TD>斯洛文尼亚</TD>
                <TD>SI</TD>
                <TD>386</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Solomon Is</TD>
                <TD>所罗门群岛</TD>
                <TD>SB</TD>
                <TD>677</TD>
                <TD>+3</TD>
            </TR>
            <TR>
                <TD>Somali</TD>
                <TD>索马里</TD>
                <TD>SO</TD>
                <TD>252</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>South Africa</TD>
                <TD>南非</TD>
                <TD>ZA</TD>
                <TD>27</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Spain</TD>
                <TD>西班牙</TD>
                <TD>ES</TD>
                <TD>34</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>Sri Lanka</TD>
                <TD>斯里兰卡</TD>
                <TD>LK</TD>
                <TD>94</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>St.Lucia</TD>
                <TD>圣卢西亚</TD>
                <TD>LC</TD>
                <TD>1758</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>St.Vincent</TD>
                <TD>圣文森特</TD>
                <TD>VC</TD>
                <TD>1784</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Sudan</TD>
                <TD>苏丹</TD>
                <TD>SD</TD>
                <TD>249</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Suriname</TD>
                <TD>苏里南</TD>
                <TD>SR</TD>
                <TD>597</TD>
                <TD>-11.3</TD>
            </TR>
            <TR>
                <TD>Swaziland</TD>
                <TD>斯威士兰</TD>
                <TD>SZ</TD>
                <TD>268</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Sweden</TD>
                <TD>瑞典</TD>
                <TD>SE</TD>
                <TD>46</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Switzerland</TD>
                <TD>瑞士</TD>
                <TD>CH</TD>
                <TD>41</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Syria</TD>
                <TD>叙利亚</TD>
                <TD>SY</TD>
                <TD>963</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Taiwan</TD>
                <TD>台湾省</TD>
                <TD>TW</TD>
                <TD>886</TD>
                <TD>0</TD>
            </TR>
            <TR>
                <TD>Tajikstan</TD>
                <TD>塔吉克斯坦</TD>
                <TD>TJ</TD>
                <TD>992</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Tanzania</TD>
                <TD>坦桑尼亚</TD>
                <TD>TZ</TD>
                <TD>255</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Thailand</TD>
                <TD>泰国</TD>
                <TD>TH</TD>
                <TD>66</TD>
                <TD>-1</TD>
            </TR>
            <TR>
                <TD>Togo</TD>
                <TD>多哥</TD>
                <TD>TG</TD>
                <TD>228</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD>Tonga</TD>
                <TD>汤加</TD>
                <TD>TO</TD>
                <TD>676</TD>
                <TD>+4</TD>
            </TR>
            <TR>
                <TD>Trinidad and Tobago</TD>
                <TD>特立尼达和多巴哥</TD>
                <TD>TT</TD>
                <TD>1809</TD>
                <TD>-12</TD>
            </TR>
            <TR>
                <TD>Tunisia</TD>
                <TD>突尼斯</TD>
                <TD>TN</TD>
                <TD>216</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Turkey</TD>
                <TD>土耳其</TD>
                <TD>TR</TD>
                <TD>90</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Turkmenistan </TD>
                <TD>土库曼斯坦</TD>
                <TD>TM</TD>
                <TD>993</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Uganda</TD>
                <TD>乌干达</TD>
                <TD>UG</TD>
                <TD>256</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Ukraine</TD>
                <TD>乌克兰</TD>
                <TD>UA</TD>
                <TD>380</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>United Arab
                        Emirates</TD>
                <TD>阿拉伯联合酋长国</TD>
                <TD>AE</TD>
                <TD>971</TD>
                <TD>-4</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>United Kiongdom</TD>
                <TD>英国</TD>
                <TD>GB</TD>
                <TD>44</TD>
                <TD>-8</TD>
            </TR>
            <TR>
                <TD><FONT color=#000000>United States
                        of America</TD>
                <TD>美国</TD>
                <TD>US</TD>
                <TD>1</TD>
                <TD>-13</TD>
            </TR>
            <TR>
                <TD>Uruguay</TD>
                <TD>乌拉圭</TD>
                <TD>UY</TD>
                <TD>598</TD>
                <TD>-10.3</TD>
            </TR>
            <TR>
                <TD>Uzbekistan</TD>
                <TD>乌兹别克斯坦</TD>
                <TD>UZ</TD>
                <TD>233</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Venezuela</TD>
                <TD>委内瑞拉</TD>
                <TD>VE</TD>
                <TD>58</TD>
                <TD>-12.3</TD>
            </TR>
            <TR>
                <TD>Vietnam</TD>
                <TD>越南</TD>
                <TD>VN</TD>
                <TD>84</TD>
                <TD>-1</TD>
            </TR>
            <TR>
                <TD>Yemen</TD>
                <TD>也门</TD>
                <TD>YE</TD>
                <TD>967</TD>
                <TD>-5</TD>
            </TR>
            <TR>
                <TD>Yugoslavia</TD>
                <TD>南斯拉夫</TD>
                <TD>YU</TD>
                <TD>381</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Zimbabwe</TD>
                <TD>津巴布韦</TD>
                <TD>ZW</TD>
                <TD>263</TD>
                <TD>-6</TD>
            </TR>
            <TR>
                <TD>Zaire</TD>
                <TD>扎伊尔</TD>
                <TD>ZR</TD>
                <TD>243</TD>
                <TD>-7</TD>
            </TR>
            <TR>
                <TD>Zambia</TD>
                <TD>赞比亚</TD>
                <TD>ZM</TD>
                <TD>260</TD>
                <TD>-6</TD>
            </TR>

        </TABLE>

    </div>
</div>
@stop